package com.q.s.quicksearch.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table THUNDER_AVSOURCE.
 */
public class ThunderAVSource implements Parcelable {

    private Long id;
    private String title;
    private String content;
    private Boolean hasMosaic;
    private Boolean marked;

    public ThunderAVSource() {
    }

    public ThunderAVSource(Long id) {
        this.id = id;
    }

    public ThunderAVSource(Long id, String title, String content, Boolean hasMosaic, Boolean marked) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.hasMosaic = hasMosaic;
        this.marked = marked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Boolean getHasMosaic() {
        return hasMosaic;
    }

    public void setHasMosaic(Boolean hasMosaic) {
        this.hasMosaic = hasMosaic;
    }

    public Boolean getMarked() {
        return marked;
    }

    public void setMarked(Boolean marked) {
        this.marked = marked;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.title);
        dest.writeString(this.content);
        dest.writeValue(this.hasMosaic);
        dest.writeValue(this.marked);
    }

    protected ThunderAVSource(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.title = in.readString();
        this.content = in.readString();
        this.hasMosaic = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.marked = (Boolean) in.readValue(Boolean.class.getClassLoader());
    }

    public static final Parcelable.Creator<ThunderAVSource> CREATOR = new Parcelable.Creator<ThunderAVSource>() {
        public ThunderAVSource createFromParcel(Parcel source) {
            return new ThunderAVSource(source);
        }

        public ThunderAVSource[] newArray(int size) {
            return new ThunderAVSource[size];
        }
    };
}
